apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
  namespace: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      restartPolicy: Always
      containers:
      - name: backend-depl
        image: thetkpark/gdsc-basic-k8s-todo-server:v2
        resources:
          limits:
            memory: "32Mi"
            cpu: "20m"
        ports:
        - containerPort: 5050
        envFrom:
          - secretRef:
              name: my-k8s-secret
